version: "3.5"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    networks:
      - cloudacademylabs
    ports:
      - "8080:8080"
networks:
  cloudacademylabs:
    name: cloudacademylabs
